name: Pre-release

on: [workflow_dispatch]

jobs:
  default:
    strategy:
      matrix:
        distro: [melodic, noetic]

    env:
      BUILDER: catkin_make_isolated
      ROS_DISTRO: ${{ matrix.distro }}
      PRERELEASE: true
      CCACHE_DIR: ${{ github.workspace }}/.base/.ccache
      CACHE_PREFIX: ${{ matrix.distro}}
    name: "${{ matrix.distro }}"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: pat-s/always-upload-cache@v2.1.3
        with:
          path: ${{ env.CCACHE_DIR }}
          key: ccache-${{ env.CACHE_PREFIX }}-${{ github.sha }}-${{ github.run_id }}
          restore-keys: |
            ccache-${{ env.CACHE_PREFIX }}-${{ github.sha }}
            ccache-${{ env.CACHE_PREFIX }}
      - run: sudo apt-get update && sudo apt-get install -y ccache
      - run: ccache -s
        name: ccache-before-ci
      - uses: ipa-mdl/industrial_ci@feature/prerelease-ccache
      - run: ccache -s
        name: ccache-after-ci
